PREFIX gn: <http://www.geonames.org/ontology#>
PREFIX sorg: <http://schema.org/>
SELECT ?v0 ?v1 ?v3 WHERE {
  ?v0 sorg:jobTitle ?v1 .
  wsdbm:City136 gn:parentCountry ?v3 .
  ?v0 sorg:nationality ?v3 .
}
