PREFIX gr: <http://purl.org/goodrelations/>
PREFIX sorg: <http://schema.org/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX wsdbm: <http://db.uwaterloo.ca/~galuc/wsdbm/>
SELECT ?v0 ?v1 ?v3 ?v4 ?v5 ?v6 ?v7 ?v8 ?v9
       ?sum_product_1_source
       ?sum_product_2_source
       ?sum_product_3_source
       ?sum_product_4_source
       ?sum_product_5_source
       ?sum_product_6_source
       ?sum_product_7_source
       ?sum_product_8_source
       ?sum_product_9_source
       ?sum_product
       ?sum
WHERE {
  ?sum_product_1_source rdf:subject ?v0 ; rdf:predicate gr:includes ; rdf:object ?v1 .
  ?sum_product_2_source rdf:subject wsdbm:Retailer4733 ; rdf:predicate gr:offers ; rdf:object ?v0 .
  ?sum_product_3_source rdf:subject ?v0 ; rdf:predicate gr:price ; rdf:object ?v3 .
  ?sum_product_4_source rdf:subject ?v0 ; rdf:predicate gr:serialNumber ; rdf:object ?v4 .
  ?sum_product_5_source rdf:subject ?v0 ; rdf:predicate gr:validFrom ; rdf:object ?v5 .
  ?sum_product_6_source rdf:subject ?v0 ; rdf:predicate gr:validThrough ; rdf:object ?v6 .
  ?sum_product_7_source rdf:subject ?v0 ; rdf:predicate sorg:eligibleQuantity ; rdf:object ?v7 .
  ?sum_product_8_source rdf:subject ?v0 ; rdf:predicate sorg:eligibleRegion ; rdf:object ?v8 .
  ?sum_product_9_source rdf:subject ?v0 ; rdf:predicate sorg:priceValidUntil ; rdf:object ?v9 .
  BIND (URI(CONCAT("http://example.org/sum_product/",
                   "?s_1=", ENCODE_FOR_URI(xsd:string(?v0)),
                   "&s_2=", ENCODE_FOR_URI(xsd:string(?v1)),
                   "&s_3=", ENCODE_FOR_URI(xsd:string(?v3)),
                   "&s_4=", ENCODE_FOR_URI(xsd:string(?v4)),
                   "&s_5=", ENCODE_FOR_URI(xsd:string(?v5)),
                   "&s_6=", ENCODE_FOR_URI(xsd:string(?v6)),
                   "&s_7=", ENCODE_FOR_URI(xsd:string(?v7)),
                   "&s_8=", ENCODE_FOR_URI(xsd:string(?v8)),
                   "&s_9=", ENCODE_FOR_URI(xsd:string(?v9))))
        AS ?sum_product )
  BIND (URI(CONCAT("http://example.org/sum/",
                   "?s_1=", ENCODE_FOR_URI(xsd:string(?v0)),
                   "&s_2=", ENCODE_FOR_URI(xsd:string(?v1)),
                   "&s_3=", ENCODE_FOR_URI(xsd:string(?v3)),
                   "&s_4=", ENCODE_FOR_URI(xsd:string(?v4)),
                   "&s_5=", ENCODE_FOR_URI(xsd:string(?v5)),
                   "&s_6=", ENCODE_FOR_URI(xsd:string(?v6)),
                   "&s_7=", ENCODE_FOR_URI(xsd:string(?v7)),
                   "&s_8=", ENCODE_FOR_URI(xsd:string(?v8)),
                   "&s_9=", ENCODE_FOR_URI(xsd:string(?v9))))
        AS ?sum )
}
