PREFIX sorg: <http://schema.org/>
PREFIX wsdbm: <http://db.uwaterloo.ca/~galuc/wsdbm/>
SELECT ?v0 ?v1 ?v2 ?v4 ?v5 ?v6 WHERE {
  GRAPH ?sum_product_1_source { ?v0 sorg:contentRating ?v1 . }
  GRAPH ?sum_product_2_source { ?v0 sorg:contentSize ?v2 . }
  GRAPH ?sum_product_3_source { ?v0 wsdbm:hasGenre wsdbm:SubGenre59 . }
  GRAPH ?sum_product_4_source { ?v4 wsdbm:makesPurchase ?v5 . }
  GRAPH ?sum_product_5_source { ?v5 wsdbm:purchaseDate ?v6 . }
  GRAPH ?sum_product_6_source { ?v5 wsdbm:purchaseFor ?v0 . }
}
