PREFIX wsdbm: <http://db.uwaterloo.ca/~galuc/wsdbm/>
PREFIX dc: <http://purl.org/dc/terms/>
PREFIX sorg: <http://schema.org/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
SELECT ?v0
WHERE {
  ?sum_product_1_source rdf:subject ?v0 ;
                        rdf:predicate dc:Location ;
			rdf:object ?v1 .
  ?sum_product_2_source rdf:subject ?v0 ;
                        rdf:predicate sorg:nationality ;
			rdf:object wsdbm:Country21 .
  ?sum_product_3_source rdf:subject ?v0 ;
                        rdf:predicate wsdbm:gender ;
			rdf:object ?v3 .
  ?sum_product_4_source rdf:subject ?v0 ;
                        rdf:predicate rdf:type ;
			rdf:object wsdbm:Role2 .
}
