PREFIX gn: <http://www.geonames.org/ontology#>
PREFIX sorg: <http://schema.org/>
PREFIX wsdbm: <http://db.uwaterloo.ca/~galuc/wsdbm/>
SELECT ?v0 ?v1 ?v3 WHERE {
  GRAPH ?sum_product_1_source { wsdbm:City126 gn:parentCountry ?v3 . }
  GRAPH ?sum_product_2_source { ?v0 sorg:nationality ?v3 . }
  OPTIONAL { GRAPH ?sum_product_3_source { ?v0 sorg:jobTitle ?v1 . } }
}
