PREFIX wsdbm: <http://db.uwaterloo.ca/~galuc/wsdbm/>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
SELECT ?v0 ?sum ?sum_product ?sum_product_1_source ?sum_product_2_source
WHERE {
  ?sum_product_1_source rdf:subject ?v0 ;
                        rdf:predicate wsdbm:likes ;
			rdf:object ?v1 .
  ?sum_product_2_source rdf:subject ?v0 ;
                        rdf:predicate wsdbm:subscribes ;
			rdf:object wsdbm:Website2059 .
  BIND (
    URI(CONCAT("http://example.org/sum_product/",
               "?s_1=", ENCODE_FOR_URI(xsd:string(?v0)),
               "&s_2=", ENCODE_FOR_URI(xsd:string(?v1))))
    AS ?sum_product )
  BIND (
    URI(CONCAT("http://example.org/sum/",
               "?s_1=", ENCODE_FOR_URI(xsd:string(?v0))))
    AS ?sum )
}
