PREFIX grp: <http://example.org/p/purl.org/goodrelations/>
PREFIX sorgp: <http://example.org/p/schema.org/>
PREFIX grps: <http://example.org/ps/purl.org/goodrelations/>
PREFIX sorgps: <http://example.org/ps/schema.org/>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX wsdbm: <http://db.uwaterloo.ca/~galuc/wsdbm/>
SELECT ?v0 ?v1 ?v3 ?v4 ?v5 ?v6 ?v7 ?v8 ?v9
       ?sum_product_1_source
       ?sum_product_2_source
       ?sum_product_3_source
       ?sum_product_4_source
       ?sum_product_5_source
       ?sum_product_6_source
       ?sum_product_7_source
       ?sum_product_8_source
       ?sum_product_9_source
       ?sum_product
       ?sum
WHERE {
  ?v0 grp:includes ?sum_product_1_source . ?sum_product_1_source grps:includes ?v1 .
  wsdbm:Retailer8811 grp:offers ?sum_product_2_source . ?sum_product_2_source grps:offers ?v0 .
  ?v0 grp:price ?sum_product_3_source . ?sum_product_3_source grps:price ?v3 .
  ?v0 grp:serialNumber ?sum_product_4_source . ?sum_product_4_source grps:serialNumber ?v4 .
  ?v0 grp:validFrom ?sum_product_5_source . ?sum_product_5_source grps:validFrom ?v5 .
  ?v0 grp:validThrough ?sum_product_6_source . ?sum_product_6_source grps:validThrough ?v6 .
  ?v0 sorgp:eligibleQuantity ?sum_product_7_source . ?sum_product_7_source sorgps:eligibleQuantity ?v7 .
  ?v0 sorgp:eligibleRegion ?sum_product_8_source . ?sum_product_8_source sorgps:eligibleRegion ?v8 .
  ?v0 sorgp:priceValidUntil ?sum_product_9_source . ?sum_product_9_source sorgps:priceValidUntil ?v9 .
  BIND (URI(CONCAT("http://example.org/sum_product/",
                   "?s_1=", ENCODE_FOR_URI(xsd:string(?v0)),
                   "&s_2=", ENCODE_FOR_URI(xsd:string(?v1)),
                   "&s_3=", ENCODE_FOR_URI(xsd:string(?v3)),
                   "&s_4=", ENCODE_FOR_URI(xsd:string(?v4)),
                   "&s_5=", ENCODE_FOR_URI(xsd:string(?v5)),
                   "&s_6=", ENCODE_FOR_URI(xsd:string(?v6)),
                   "&s_7=", ENCODE_FOR_URI(xsd:string(?v7)),
                   "&s_8=", ENCODE_FOR_URI(xsd:string(?v8)),
                   "&s_9=", ENCODE_FOR_URI(xsd:string(?v9))))
        AS ?sum_product )
  BIND (URI(CONCAT("http://example.org/sum/",
                   "?s_1=", ENCODE_FOR_URI(xsd:string(?v0)),
                   "&s_2=", ENCODE_FOR_URI(xsd:string(?v1)),
                   "&s_3=", ENCODE_FOR_URI(xsd:string(?v3)),
                   "&s_4=", ENCODE_FOR_URI(xsd:string(?v4)),
                   "&s_5=", ENCODE_FOR_URI(xsd:string(?v5)),
                   "&s_6=", ENCODE_FOR_URI(xsd:string(?v6)),
                   "&s_7=", ENCODE_FOR_URI(xsd:string(?v7)),
                   "&s_8=", ENCODE_FOR_URI(xsd:string(?v8)),
                   "&s_9=", ENCODE_FOR_URI(xsd:string(?v9))))
        AS ?sum )
}
