PREFIX gn: <http://www.geonames.org/ontology#>
PREFIX sorg: <http://schema.org/>
PREFIX wsdbm: <http://db.uwaterloo.ca/~galuc/wsdbm/>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
SELECT ?v0 ?v1 ?v3
       ?sum_osum_1_product_1_source
       ?sum_osum_1_product_2_source
       ?sum_osum_1_product_3_source
       ?sum_osum_1_product
       ?sum_osum_2_minus_1_product_1_source
       ?sum_osum_2_minus_1_product_2_source
       ?sum_osum_2_minus_1_product
       ?sum_osum_2_minus_2_sum_source
       ?sum_osum_2_minus_2_sum
       ?sum_osum_2_minus
       ?sum
WHERE {
  {
    ?sum_osum_1_product_1_source rdf:subject wsdbm:City136 ; rdf:predicate gn:parentCountry ; rdf:object ?v3 .
    ?sum_osum_1_product_2_source rdf:subject ?v0 ; rdf:predicate sorg:nationality ; rdf:object ?v3 .
    ?sum_osum_1_product_3_source rdf:subject ?v0 ; rdf:predicate sorg:jobTitle ; rdf:object ?v1 .
    BIND (URI(CONCAT("http://example.org/sum_osum_1_product/",
                     "?s_1=", ENCODE_FOR_URI(xsd:string(?v0)),
                     "&s_2=", ENCODE_FOR_URI(xsd:string(?v1)),
                     "&s_3=", ENCODE_FOR_URI(xsd:string(?v3))))
          AS ?sum_osum_1_product )
  }
  UNION
  {
    ?sum_osum_2_minus_1_product_1_source rdf:subject wsdbm:City136 ; rdf:predicate gn:parentCountry ; rdf:object ?v3 .
    ?sum_osum_2_minus_1_product_2_source rdf:subject ?v0 ; rdf:predicate sorg:nationality ; rdf:object ?v3 .
    OPTIONAL { ?sum_osum_2_minus_2_sum_source rdf:subject ?v0 ; rdf:predicate sorg:jobTitle ; rdf:object ?v1 . }
    BIND (URI(CONCAT("http://example.org/sum_osum_2_minus/",
                     "?s_1=", ENCODE_FOR_URI(xsd:string(?v0)),
                     "&s_2=", ENCODE_FOR_URI(xsd:string(?v3))))
          AS ?sum_osum_2_minus )
    BIND (URI(CONCAT("http://example.org/sum_osum_2_minus_2_sum/",
                     "?s_1=", ENCODE_FOR_URI(xsd:string(?v0)),
                     "&s_2=", ENCODE_FOR_URI(xsd:string(?v3))))
          AS ?sum_osum_2_minus_2_sum )
    BIND (URI(CONCAT("http://example.org/sum_osum_2_minus_1_product/",
                     "?s_1=", ENCODE_FOR_URI(xsd:string(?v0)),
                     "&s_2=", ENCODE_FOR_URI(xsd:string(?v3))))
          AS ?sum_osum_2_minus_1_product )
  }
  BIND (URI(CONCAT("http://example.org/sum/",
                   "?s_1=", ENCODE_FOR_URI(xsd:string(?v0)),
                   "&s_2=", ENCODE_FOR_URI(xsd:string(?v3)),
                   "&s_3=", COALESCE(ENCODE_FOR_URI(xsd:string(?v1)), "")))
        AS ?sum )
}
