PREFIX wsdbm: <http://db.uwaterloo.ca/~galuc/wsdbm/>
PREFIX wsdbmp: <http://example.org/p/db.uwaterloo.ca/~galuc/wsdbm/>
PREFIX wsdbmps: <http://example.org/ps/db.uwaterloo.ca/~galuc/wsdbm/>
PREFIX dc: <http://purl.org/dc/terms/>
PREFIX dcp: <http://example.org/p/purl.org/dc/terms/>
PREFIX dcps: <http://example.org/ps/purl.org/dc/terms/>
PREFIX foaf: <http://xmlns.com/foaf/>
PREFIX foafp: <http://example.org/p/xmlns.com/foaf/>
PREFIX foafps: <http://example.org/ps/xmlns.com/foaf/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfp: <http://example.org/p/www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfps: <http://example.org/ps/www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
SELECT ?v0
  ?sum
  ?sum_product ?sum_product_1_source ?sum_product_2_source ?sum_product_3_source
  ?sum_product_4_source ?sum_product_5_source ?sum_product_6_source
WHERE {
  ?v0 wsdbmp:likes ?sum_product_1_source .
  ?sum_product_1_source wsdbmps:likes ?v1 .

  ?v0 wsdbmp:friendOf ?sum_product_2_source .
  ?sum_product_2_source wsdbmps:friendOf ?v2 .

  ?v0 dcp:Location ?sum_product_3_source .
  ?sum_product_3_source dcps:Location ?v3 .

  ?v0 foafp:age ?sum_product_4_source .
  ?sum_product_4_source foafps:age ?v4 .

  ?v0 wsdbmp:gender ?sum_product_5_source .
  ?sum_product_5_source wsdbmps:gender ?v5 .

  ?v0 foafp:givenName ?sum_product_6_source .
  ?sum_product_6_source foafps:givenName ?v6 .
  
  BIND (
        URI(CONCAT("http://example.org/sum_product/",
                   "?s_1=", ENCODE_FOR_URI(xsd:string(?v0)),
                   "&s_2=", ENCODE_FOR_URI(xsd:string(?v1)),
                   "&s_3=", ENCODE_FOR_URI(xsd:string(?v2)),
                   "&s_4=", ENCODE_FOR_URI(xsd:string(?v3)),
                   "&s_5=", ENCODE_FOR_URI(xsd:string(?v4)),
                   "&s_6=", ENCODE_FOR_URI(xsd:string(?v5))))
        AS ?sum_product )
  BIND (
    URI(CONCAT("http://example.org/sum/",
               "?s_1=", ENCODE_FOR_URI(xsd:string(?v0))))
    AS ?sum )
}
