PREFIX wsdbm: <http://db.uwaterloo.ca/~galuc/wsdbm/>
PREFIX wsdbmp: <http://example.org/p/db.uwaterloo.ca/~galuc/wsdbm/>
PREFIX wsdbmps: <http://example.org/ps/db.uwaterloo.ca/~galuc/wsdbm/>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
SELECT ?v0 ?v1
       ?sum_osum_1_product_1_source
       ?sum_osum_1_product_2_source
       ?sum_osum_1_product
       ?sum_osum_2_minus_1_source
       ?sum_osum_2_minus_2_sum_source
       ?sum_osum_2_minus_2_sum
       ?sum_osum_2_minus
       ?sum
WHERE {
  {
    ?v0 wsdbmp:subscribes ?sum_osum_1_product_1_source . ?sum_osum_1_product_1_source wsdbmps:subscribes wsdbm:Website5135 .
    ?v0 wsdbmp:likes ?sum_osum_2_product_2_source . ?sum_osum_2_product_2_source wsdbmps:likes ?v1 .
    BIND (URI(CONCAT("http://example.org/sum_product/",
                     "?s_1=", ENCODE_FOR_URI(xsd:string(?v0)),
                     "&s_3=", ENCODE_FOR_URI(xsd:string(?v1))))
          AS ?sum_osum_1_product )
  }
  UNION
  {
    ?v0 wsdbmp:subscribes ?sum_osum_2_minus_1_source . ?sum_osum_2_minus_1_source wsdbmps:subscribes wsdbm:Website5135 .
    OPTIONAL { ?v0 wsdbmp:likes ?sum_osum_2_minus_2_sum_source . ?sum_osum_2_minus_2_sum_source wsdbmps:likes ?v1 . }
    BIND (URI(CONCAT("http://example.org/sum_osum_2_minus/",
                     "?s_1=", ENCODE_FOR_URI(xsd:string(?v0))))
          AS ?sum_osum_2_minus )
    BIND (URI(CONCAT("http://example.org/sum_osum_2_minus_2_sum/",
                     "?s_1=", ENCODE_FOR_URI(xsd:string(?v0))))
          AS ?sum_osum_2_minus_2_sum )
  }
  BIND (URI(CONCAT("http://example.org/sum/",
                   "?s_1=", ENCODE_FOR_URI(xsd:string(?v0)),
                   "&s_2=", COALESCE(ENCODE_FOR_URI(xsd:string(?v1)), "")))
        AS ?sum )
}
