PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX sorg: <http://schema.org/>
PREFIX wsdbm: <http://db.uwaterloo.ca/~galuc/wsdbm/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
SELECT ?v0 ?v1 ?v2 WHERE {
  ?sum_product_1_source rdf:subject ?v0 ; rdf:predicate rdf:type ; rdf:object ?v1 .
  ?sum_product_2_source rdf:subject ?v0 ; rdf:predicate sorg:text ; rdf:object ?v2 .
  ?sum_product_3_source rdf:subject wsdbm:User9321 ; rdf:predicate wsdbm:likes ; rdf:object ?v0 .
}
