PREFIX gr: <http://purl.org/goodrelations/>
PREFIX sorg: <http://schema.org/>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX wsdbm: <http://db.uwaterloo.ca/~galuc/wsdbm/>
SELECT ?v0 ?v1 ?v3 ?v4 ?v5 ?v6 ?v7 ?v8 ?v9
       ?sum_product_1_source
       ?sum_product_2_source
       ?sum_product_3_source
       ?sum_product_4_source
       ?sum_product_5_source
       ?sum_product_6_source
       ?sum_product_7_source
       ?sum_product_8_source
       ?sum_product_9_source
       ?sum_product
       ?sum
WHERE {
  GRAPH ?sum_product_1_source { ?v0 gr:includes ?v1 . }
  GRAPH ?sum_product_2_source { wsdbm:Retailer3777 gr:offers ?v0 . }
  GRAPH ?sum_product_3_source { ?v0 gr:price ?v3 . }
  GRAPH ?sum_product_4_source { ?v0 gr:serialNumber ?v4 . }
  GRAPH ?sum_product_5_source { ?v0 gr:validFrom ?v5 . }
  GRAPH ?sum_product_6_source { ?v0 gr:validThrough ?v6 . }
  GRAPH ?sum_product_7_source { ?v0 sorg:eligibleQuantity ?v7 . }
  GRAPH ?sum_product_8_source { ?v0 sorg:eligibleRegion ?v8 . }
  GRAPH ?sum_product_9_source { ?v0 sorg:priceValidUntil ?v9 . }
  BIND (URI(CONCAT("http://example.org/sum_product/",
                   "?s_1=", ENCODE_FOR_URI(xsd:string(?v0)),
                   "&s_2=", ENCODE_FOR_URI(xsd:string(?v1)),
                   "&s_3=", ENCODE_FOR_URI(xsd:string(?v3)),
                   "&s_4=", ENCODE_FOR_URI(xsd:string(?v4)),
                   "&s_5=", ENCODE_FOR_URI(xsd:string(?v5)),
                   "&s_6=", ENCODE_FOR_URI(xsd:string(?v6)),
                   "&s_7=", ENCODE_FOR_URI(xsd:string(?v7)),
                   "&s_8=", ENCODE_FOR_URI(xsd:string(?v8)),
                   "&s_9=", ENCODE_FOR_URI(xsd:string(?v9))))
        AS ?sum_product )
  BIND (URI(CONCAT("http://example.org/sum/",
                   "?s_1=", ENCODE_FOR_URI(xsd:string(?v0)),
                   "&s_2=", ENCODE_FOR_URI(xsd:string(?v1)),
                   "&s_3=", ENCODE_FOR_URI(xsd:string(?v3)),
                   "&s_4=", ENCODE_FOR_URI(xsd:string(?v4)),
                   "&s_5=", ENCODE_FOR_URI(xsd:string(?v5)),
                   "&s_6=", ENCODE_FOR_URI(xsd:string(?v6)),
                   "&s_7=", ENCODE_FOR_URI(xsd:string(?v7)),
                   "&s_8=", ENCODE_FOR_URI(xsd:string(?v8)),
                   "&s_9=", ENCODE_FOR_URI(xsd:string(?v9))))
        AS ?sum )
}
