PREFIX sorgp: <http://schema.org/>
PREFIX sorgps: <http://schema.org/>
PREFIX revp: <http://purl.org/stuff/rev#>
PREFIX revps: <http://purl.org/stuff/rev#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
SELECT ?v0 ?v4 ?v6 ?v7
       ?sum_product_1_source
       ?sum_product_2_source
       ?sum_product_3_source
       ?sum_product_4_source
       ?sum_product_5_source
       ?sum_product_6_source
       ?sum_product_7_source
       ?sum_product_8_source
       ?sum_product
       ?sum
WHERE {
  ?v0 sorgp:caption ?sum_product_1_source . ?sum_product_1_source sorgps:caption ?v1 .
  ?v0 sorgp:text ?sum_product_2_source . ?sum_product_2_source sorgps:text ?v2 .
  ?v0 sorgp:contentRating ?sum_product_3_source . ?sum_product_3_source sorgps:contentRating ?v3 .
  ?v0 revp:hasReview ?sum_product_4_source . ?sum_product_4_source revps:hasReview ?v4 .
  ?v4 revp:title ?sum_product_5_source . ?sum_product_5_source revps:title ?v5 .
  ?v4 revp:reviewer ?sum_product_6_source . ?sum_product_6_source revps:reviewer ?v6 .
  ?v7 sorgp:actor ?sum_product_7_source . ?sum_product_7_source sorgps:actor ?v6 .
  ?v7 sorgp:language ?sum_product_8_source . ?sum_product_8_source sorgps:language ?v8 .
  BIND (URI(CONCAT("http://example.org/sum_product/",
                   "?s_1=", ENCODE_FOR_URI(xsd:string(?v0)),
                   "&s_2=", ENCODE_FOR_URI(xsd:string(?v1)),
                   "&s_3=", ENCODE_FOR_URI(xsd:string(?v2)),
                   "&s_4=", ENCODE_FOR_URI(xsd:string(?v3)),
                   "&s_5=", ENCODE_FOR_URI(xsd:string(?v4)),
                   "&s_6=", ENCODE_FOR_URI(xsd:string(?v5)),
                   "&s_7=", ENCODE_FOR_URI(xsd:string(?v6)),
                   "&s_8=", ENCODE_FOR_URI(xsd:string(?v7)),
                   "&s_9=", ENCODE_FOR_URI(xsd:string(?v8))))
        AS ?sum_product )
  BIND (URI(CONCAT("http://example.org/sum/",
                   "?s_1=", ENCODE_FOR_URI(xsd:string(?v0)),
                   "&s_2=", ENCODE_FOR_URI(xsd:string(?v4)),
                   "&s_3=", ENCODE_FOR_URI(xsd:string(?v6)),
                   "&s_4=", ENCODE_FOR_URI(xsd:string(?v7))))
        AS ?sum )
}
