PREFIX ogp: <http://example.org/p/ogp.me/ns#>
PREFIX sorgp: <http://example.org/p/schema.org/>
PREFIX ogps: <http://example.org/ps/ogp.me/ns#>
PREFIX sorgps: <http://example.org/ps/schema.org/>
PREFIX wsdbm: <http://db.uwaterloo.ca/~galuc/wsdbm/>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
SELECT ?v0 ?v2
       ?sum_osum_1_product_1_source
       ?sum_osum_1_product_2_source
       ?sum_osum_1_product
       ?sum_osum_2_minus_1_source
       ?sum_osum_2_minus_2_sum_source
       ?sum_osum_2_minus_2_sum
       ?sum_osum_2_minus
       ?sum
WHERE {
  {
    ?v0 ogp:tag ?sum_osum_1_product_1_source . ?sum_osum_1_product_1_source ogps:tag wsdbm:Topic99 .
    ?v0 sorgp:caption ?sum_osum_1_product_2_source . ?sum_osum_1_product_2_source sorgps:caption ?v2 .
    BIND (URI(CONCAT("http://example.org/sum_product/",
                     "?s_1=", ENCODE_FOR_URI(xsd:string(?v0)),
                     "&s_3=", ENCODE_FOR_URI(xsd:string(?v2))))
          AS ?sum_osum_1_product )
  }
  UNION
  {
    ?v0 ogp:tag ?sum_osum_2_minus_1_source . ?sum_osum_2_minus_1_source ogps:tag wsdbm:Topic99 .
    OPTIONAL { ?v0 sorgp:caption ?sum_osum_2_minus_2_sum_source . ?sum_osum_2_minus_2_sum_source sorgps:caption ?v2 . }
    BIND (URI(CONCAT("http://example.org/sum_osum_2_minus/",
                     "?s_1=", ENCODE_FOR_URI(xsd:string(?v0))))
          AS ?sum_osum_2_minus )
    BIND (URI(CONCAT("http://example.org/sum_osum_2_minus_2_sum/",
                     "?s_1=", ENCODE_FOR_URI(xsd:string(?v0))))
          AS ?sum_osum_2_minus_2_sum )
  }
  BIND (URI(CONCAT("http://example.org/sum/",
                   "?s_1=", ENCODE_FOR_URI(xsd:string(?v0)),
                   "&s_2=", COALESCE(ENCODE_FOR_URI(xsd:string(?v2)), "")))
        AS ?sum )
}
