PREFIX foafp: <http://example.org/p/xmlns.com/foaf/>
PREFIX grp: <http://example.org/p/purl.org/goodrelations/>
PREFIX ogp: <http://example.org/p/ogp.me/ns#>
PREFIX sorgp: <http://example.org/p/schema.org/>
PREFIX wsdbmp: <http://example.org/p/db.uwaterloo.ca/~galuc/wsdbm/>
PREFIX foafps: <http://example.org/ps/xmlns.com/foaf/>
PREFIX grps: <http://example.org/ps/purl.org/goodrelations/>
PREFIX ogps: <http://example.org/ps/ogp.me/ns#>
PREFIX sorgps: <http://example.org/ps/schema.org/>
PREFIX wsdbmps: <http://example.org/ps/db.uwaterloo.ca/~galuc/wsdbm/>
PREFIX wsdbm: <http://db.uwaterloo.ca/~galuc/wsdbm/>
SELECT ?v0 ?v1 ?v2 ?v4 ?v5 ?v6 ?v7 ?v8 WHERE {
  ?v0 foafp:homepage ?sum_product_1_source . ?sum_product_1_source foafps:homepage ?v1 .
  ?v2 grp:includes ?sum_product_2_source . ?sum_product_2_source grps:includes ?v0 .
  ?v0 ogp:tag ?sum_product_3_source . ?sum_product_3_source ogps:tag wsdbm:Topic80 .
  ?v0 sorgp:description ?sum_product_4_source . ?sum_product_4_source sorgps:description ?v4 .
  ?v0 sorgp:contentSize ?sum_product_5_source . ?sum_product_5_source sorgps:contentSize ?v8 .
  ?v1 sorgp:url ?sum_product_6_source . ?sum_product_6_source sorgps:url ?v5 .
  ?v1 wsdbmp:hits ?sum_product_7_source . ?sum_product_7_source wsdbmps:hits ?v6 .
  ?v1 sorgp:language ?sum_product_8_source . ?sum_product_8_source sorgps:language wsdbm:Language0 .
  ?v7 wsdbmp:likes ?sum_product_9_source . ?sum_product_9_source wsdbmps:likes ?v0 .
}
